# Generated by Django 4.0.4 on 2022-05-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=60)),
                ('endereco', models.CharField(max_length=240)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=240)),
                ('cep', models.CharField(max_length=9)),
                ('cidade', models.CharField(max_length=60)),
                ('estado', models.CharField(max_length=60)),
                ('create_data', models.DateField(auto_now_add=True)),
                ('update_data', models.DateField(auto_now=True)),
            ],
        ),
    ]
