# Generated by Django 4.0.4 on 2022-05-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contatos', '0002_alter_contato_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='cep',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.IntegerField(max_length=11),
        ),
    ]
