# Generated by Django 4.0.4 on 2022-05-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contatos', '0004_alter_contato_bairro_alter_contato_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='create_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='update_data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
