# Generated by Django 4.0.4 on 2022-05-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contatos', '0005_alter_contato_create_data_alter_contato_update_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('create_data', models.DateTimeField(auto_now_add=True)),
                ('update_data', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contato',
            name='cep',
            field=models.IntegerField(),
        ),
    ]
