# Generated by Django 4.0.4 on 2022-05-09 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contatos', '0006_grupo_alter_contato_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Contatos.grupo'),
            preserve_default=False,
        ),
    ]
