# Generated by Django 4.0.4 on 2022-05-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contatos', '0007_contato_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='cep',
            field=models.CharField(max_length=9),
        ),
    ]
