# Generated by Django 4.0.4 on 2022-05-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contatos', '0011_alter_contato_create_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='create_data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
